//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class AgentFeedbackMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/AgentFeedback";
        public override string RosMessageName => k_RosMessageName;

        public string id;
        public Geometry.Vector3Msg force;
        public string social_state;
        public double vmax;

        public AgentFeedbackMsg()
        {
            this.id = "";
            this.force = new Geometry.Vector3Msg();
            this.social_state = "";
            this.vmax = 0.0;
        }

        public AgentFeedbackMsg(string id, Geometry.Vector3Msg force, string social_state, double vmax)
        {
            this.id = id;
            this.force = force;
            this.social_state = social_state;
            this.vmax = vmax;
        }

        public static AgentFeedbackMsg Deserialize(MessageDeserializer deserializer) => new AgentFeedbackMsg(deserializer);

        private AgentFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            this.force = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.social_state);
            deserializer.Read(out this.vmax);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.force);
            serializer.Write(this.social_state);
            serializer.Write(this.vmax);
        }

        public override string ToString()
        {
            return "AgentFeedbackMsg: " +
            "\nid: " + id.ToString() +
            "\nforce: " + force.ToString() +
            "\nsocial_state: " + social_state.ToString() +
            "\nvmax: " + vmax.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
