//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class AgentFeedbacksMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/AgentFeedbacks";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public AgentFeedbackMsg[] agents;

        public AgentFeedbacksMsg()
        {
            this.header = new HeaderMsg();
            this.agents = new AgentFeedbackMsg[0];
        }

        public AgentFeedbacksMsg(HeaderMsg header, AgentFeedbackMsg[] agents)
        {
            this.header = header;
            this.agents = agents;
        }

        public static AgentFeedbacksMsg Deserialize(MessageDeserializer deserializer) => new AgentFeedbacksMsg(deserializer);

        private AgentFeedbacksMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.agents, AgentFeedbackMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.agents);
            serializer.Write(this.agents);
        }

        public override string ToString()
        {
            return "AgentFeedbacksMsg: " +
            "\nheader: " + header.ToString() +
            "\nagents: " + System.String.Join(", ", agents.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
