//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class AgentGroupsMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/AgentGroups";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public AgentGroupMsg[] groups;

        public AgentGroupsMsg()
        {
            this.header = new HeaderMsg();
            this.groups = new AgentGroupMsg[0];
        }

        public AgentGroupsMsg(HeaderMsg header, AgentGroupMsg[] groups)
        {
            this.header = header;
            this.groups = groups;
        }

        public static AgentGroupsMsg Deserialize(MessageDeserializer deserializer) => new AgentGroupsMsg(deserializer);

        private AgentGroupsMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.groups, AgentGroupMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.groups);
            serializer.Write(this.groups);
        }

        public override string ToString()
        {
            return "AgentGroupsMsg: " +
            "\nheader: " + header.ToString() +
            "\ngroups: " + System.String.Join(", ", groups.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
