//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class AgentGroupMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/AgentGroup";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public string group_id;
        public double age;
        public string[] members;
        public Geometry.PoseMsg center_of_mass;

        public AgentGroupMsg()
        {
            this.header = new HeaderMsg();
            this.group_id = "";
            this.age = 0.0;
            this.members = new string[0];
            this.center_of_mass = new Geometry.PoseMsg();
        }

        public AgentGroupMsg(HeaderMsg header, string group_id, double age, string[] members, Geometry.PoseMsg center_of_mass)
        {
            this.header = header;
            this.group_id = group_id;
            this.age = age;
            this.members = members;
            this.center_of_mass = center_of_mass;
        }

        public static AgentGroupMsg Deserialize(MessageDeserializer deserializer) => new AgentGroupMsg(deserializer);

        private AgentGroupMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.group_id);
            deserializer.Read(out this.age);
            deserializer.Read(out this.members, deserializer.ReadLength());
            this.center_of_mass = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.group_id);
            serializer.Write(this.age);
            serializer.WriteLength(this.members);
            serializer.Write(this.members);
            serializer.Write(this.center_of_mass);
        }

        public override string ToString()
        {
            return "AgentGroupMsg: " +
            "\nheader: " + header.ToString() +
            "\ngroup_id: " + group_id.ToString() +
            "\nage: " + age.ToString() +
            "\nmembers: " + System.String.Join(", ", members.ToList()) +
            "\ncenter_of_mass: " + center_of_mass.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
