//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class ObstacleMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/Obstacle";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        //  type can be one of the following: "shelf"
        public string type;
        public Geometry.PoseMsg pose;
        public double interaction_radius;
        public string yaml_path;

        public ObstacleMsg()
        {
            this.name = "";
            this.type = "";
            this.pose = new Geometry.PoseMsg();
            this.interaction_radius = 0.0;
            this.yaml_path = "";
        }

        public ObstacleMsg(string name, string type, Geometry.PoseMsg pose, double interaction_radius, string yaml_path)
        {
            this.name = name;
            this.type = type;
            this.pose = pose;
            this.interaction_radius = interaction_radius;
            this.yaml_path = yaml_path;
        }

        public static ObstacleMsg Deserialize(MessageDeserializer deserializer) => new ObstacleMsg(deserializer);

        private ObstacleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.type);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.interaction_radius);
            deserializer.Read(out this.yaml_path);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.type);
            serializer.Write(this.pose);
            serializer.Write(this.interaction_radius);
            serializer.Write(this.yaml_path);
        }

        public override string ToString()
        {
            return "ObstacleMsg: " +
            "\nname: " + name.ToString() +
            "\ntype: " + type.ToString() +
            "\npose: " + pose.ToString() +
            "\ninteraction_radius: " + interaction_radius.ToString() +
            "\nyaml_path: " + yaml_path.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
