//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class ObstaclesMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/Obstacles";
        public override string RosMessageName => k_RosMessageName;

        //  A collection of interactive obstacles
        public HeaderMsg header;
        public ObstacleMsg[] obstacles;

        public ObstaclesMsg()
        {
            this.header = new HeaderMsg();
            this.obstacles = new ObstacleMsg[0];
        }

        public ObstaclesMsg(HeaderMsg header, ObstacleMsg[] obstacles)
        {
            this.header = header;
            this.obstacles = obstacles;
        }

        public static ObstaclesMsg Deserialize(MessageDeserializer deserializer) => new ObstaclesMsg(deserializer);

        private ObstaclesMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.obstacles, ObstacleMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.obstacles);
            serializer.Write(this.obstacles);
        }

        public override string ToString()
        {
            return "ObstaclesMsg: " +
            "\nheader: " + header.ToString() +
            "\nobstacles: " + System.String.Join(", ", obstacles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
