//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class PedsimAgentsDataframeMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/PedsimAgentsDataframe";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public AgentStateMsg[] agent_states;
        public RobotStateMsg[] robot_states;
        public WaypointMsg[] simulated_waypoints;
        public AgentGroupMsg[] simulated_groups;
        public ObstacleMsg[] obstacles;
        public WallMsg[] walls;

        public PedsimAgentsDataframeMsg()
        {
            this.header = new HeaderMsg();
            this.agent_states = new AgentStateMsg[0];
            this.robot_states = new RobotStateMsg[0];
            this.simulated_waypoints = new WaypointMsg[0];
            this.simulated_groups = new AgentGroupMsg[0];
            this.obstacles = new ObstacleMsg[0];
            this.walls = new WallMsg[0];
        }

        public PedsimAgentsDataframeMsg(HeaderMsg header, AgentStateMsg[] agent_states, RobotStateMsg[] robot_states, WaypointMsg[] simulated_waypoints, AgentGroupMsg[] simulated_groups, ObstacleMsg[] obstacles, WallMsg[] walls)
        {
            this.header = header;
            this.agent_states = agent_states;
            this.robot_states = robot_states;
            this.simulated_waypoints = simulated_waypoints;
            this.simulated_groups = simulated_groups;
            this.obstacles = obstacles;
            this.walls = walls;
        }

        public static PedsimAgentsDataframeMsg Deserialize(MessageDeserializer deserializer) => new PedsimAgentsDataframeMsg(deserializer);

        private PedsimAgentsDataframeMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.agent_states, AgentStateMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.robot_states, RobotStateMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.simulated_waypoints, WaypointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.simulated_groups, AgentGroupMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.obstacles, ObstacleMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.walls, WallMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.agent_states);
            serializer.Write(this.agent_states);
            serializer.WriteLength(this.robot_states);
            serializer.Write(this.robot_states);
            serializer.WriteLength(this.simulated_waypoints);
            serializer.Write(this.simulated_waypoints);
            serializer.WriteLength(this.simulated_groups);
            serializer.Write(this.simulated_groups);
            serializer.WriteLength(this.obstacles);
            serializer.Write(this.obstacles);
            serializer.WriteLength(this.walls);
            serializer.Write(this.walls);
        }

        public override string ToString()
        {
            return "PedsimAgentsDataframeMsg: " +
            "\nheader: " + header.ToString() +
            "\nagent_states: " + System.String.Join(", ", agent_states.ToList()) +
            "\nrobot_states: " + System.String.Join(", ", robot_states.ToList()) +
            "\nsimulated_waypoints: " + System.String.Join(", ", simulated_waypoints.ToList()) +
            "\nsimulated_groups: " + System.String.Join(", ", simulated_groups.ToList()) +
            "\nobstacles: " + System.String.Join(", ", obstacles.ToList()) +
            "\nwalls: " + System.String.Join(", ", walls.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
