//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class SemanticDatumMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/SemanticDatum";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg location;
        public float evidence;

        public SemanticDatumMsg()
        {
            this.location = new Geometry.PointMsg();
            this.evidence = 0.0f;
        }

        public SemanticDatumMsg(Geometry.PointMsg location, float evidence)
        {
            this.location = location;
            this.evidence = evidence;
        }

        public static SemanticDatumMsg Deserialize(MessageDeserializer deserializer) => new SemanticDatumMsg(deserializer);

        private SemanticDatumMsg(MessageDeserializer deserializer)
        {
            this.location = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.evidence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.location);
            serializer.Write(this.evidence);
        }

        public override string ToString()
        {
            return "SemanticDatumMsg: " +
            "\nlocation: " + location.ToString() +
            "\nevidence: " + evidence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
