//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class SemanticDataMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/SemanticData";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public SemanticDatumMsg[] points;
        public string type;

        public SemanticDataMsg()
        {
            this.header = new Std.HeaderMsg();
            this.points = new SemanticDatumMsg[0];
            this.type = "";
        }

        public SemanticDataMsg(Std.HeaderMsg header, SemanticDatumMsg[] points, string type)
        {
            this.header = header;
            this.points = points;
            this.type = type;
        }

        public static SemanticDataMsg Deserialize(MessageDeserializer deserializer) => new SemanticDataMsg(deserializer);

        private SemanticDataMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.points, SemanticDatumMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.points);
            serializer.Write(this.points);
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "SemanticDataMsg: " +
            "\nheader: " + header.ToString() +
            "\npoints: " + System.String.Join(", ", points.ToList()) +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
