//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class SocialRelationsMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/SocialRelations";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        //  All social relations of all tracks in the current time step.
        //  There might be multiple social relations per pair of tracks.
        public SocialRelationMsg[] elements;

        public SocialRelationsMsg()
        {
            this.header = new Std.HeaderMsg();
            this.elements = new SocialRelationMsg[0];
        }

        public SocialRelationsMsg(Std.HeaderMsg header, SocialRelationMsg[] elements)
        {
            this.header = header;
            this.elements = elements;
        }

        public static SocialRelationsMsg Deserialize(MessageDeserializer deserializer) => new SocialRelationsMsg(deserializer);

        private SocialRelationsMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.elements, SocialRelationMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.elements);
            serializer.Write(this.elements);
        }

        public override string ToString()
        {
            return "SocialRelationsMsg: " +
            "\nheader: " + header.ToString() +
            "\nelements: " + System.String.Join(", ", elements.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
