//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class SocialActivityMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/SocialActivity";
        public override string RosMessageName => k_RosMessageName;

        public string type;
        //  see constants below
        public float confidence;
        //  detection confidence
        public string[] track_ids;
        //  IDs of all person tracks involved in the activity, might be one or multiple
        //  Constants for social activity type (just examples at the moment)
        public const string TYPE_SHOPPING = "shopping";
        public const string TYPE_STANDING = "standing";
        public const string TYPE_TALKING = "talking";
        public const string TYPE_RUNNING = "running";
        public const string TYPE_INDIVIDUAL_MOVING = "individual_moving";
        public const string TYPE_WAITING_IN_QUEUE = "waiting_in_queue";
        public const string TYPE_LOOKING_AT_INFORMATION_SCREEN = "looking_at_information_screen";
        public const string TYPE_LOOKING_AT_KIOSK = "looking_at_kiosk";
        public const string TYPE_GROUP_ASSEMBLING = "group_assembling";
        public const string TYPE_GROUP_MOVING = "group_moving";
        public const string TYPE_FLOW_WITH_ROBOT = "flow";
        public const string TYPE_ANTIFLOW_AGAINST_ROBOT = "antiflow";
        public const string TYPE_WAITING_FOR_OTHERS = "waiting_for_others";
        // string      TYPE_COMMUNICATING = communicating
        // string      TYPE_TAKING_PHOTOGRAPH = taking_photograph
        // string      TYPE_TALKING_ON_PHONE = talking_on_phone

        public SocialActivityMsg()
        {
            this.type = "";
            this.confidence = 0.0f;
            this.track_ids = new string[0];
        }

        public SocialActivityMsg(string type, float confidence, string[] track_ids)
        {
            this.type = type;
            this.confidence = confidence;
            this.track_ids = track_ids;
        }

        public static SocialActivityMsg Deserialize(MessageDeserializer deserializer) => new SocialActivityMsg(deserializer);

        private SocialActivityMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            deserializer.Read(out this.confidence);
            deserializer.Read(out this.track_ids, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.confidence);
            serializer.WriteLength(this.track_ids);
            serializer.Write(this.track_ids);
        }

        public override string ToString()
        {
            return "SocialActivityMsg: " +
            "\ntype: " + type.ToString() +
            "\nconfidence: " + confidence.ToString() +
            "\ntrack_ids: " + System.String.Join(", ", track_ids.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
