//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class SocialRelationMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/SocialRelation";
        public override string RosMessageName => k_RosMessageName;

        public string type;
        //  e.g. mother-son relationship, romantic relationship, etc.
        public float strength;
        //  relationship strength between 0.0 and 1.0
        public string track1_id;
        public string track2_id;
        //  Constants for type (just examples at the moment)
        public const string TYPE_SPATIAL = "spatial";
        public const string TYPE_ROMANTIC = "romantic";
        public const string TYPE_PARENT_CHILD = "parent_child";
        public const string TYPE_FRIENDSHIP = "friendship";

        public SocialRelationMsg()
        {
            this.type = "";
            this.strength = 0.0f;
            this.track1_id = "";
            this.track2_id = "";
        }

        public SocialRelationMsg(string type, float strength, string track1_id, string track2_id)
        {
            this.type = type;
            this.strength = strength;
            this.track1_id = track1_id;
            this.track2_id = track2_id;
        }

        public static SocialRelationMsg Deserialize(MessageDeserializer deserializer) => new SocialRelationMsg(deserializer);

        private SocialRelationMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            deserializer.Read(out this.strength);
            deserializer.Read(out this.track1_id);
            deserializer.Read(out this.track2_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.strength);
            serializer.Write(this.track1_id);
            serializer.Write(this.track2_id);
        }

        public override string ToString()
        {
            return "SocialRelationMsg: " +
            "\ntype: " + type.ToString() +
            "\nstrength: " + strength.ToString() +
            "\ntrack1_id: " + track1_id.ToString() +
            "\ntrack2_id: " + track2_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
