//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class SocialActivitiesMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/SocialActivities";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        //  All social activities that have been detected in the current time step,
        //  within sensor range of the robot.
        public SocialActivityMsg[] elements;

        public SocialActivitiesMsg()
        {
            this.header = new Std.HeaderMsg();
            this.elements = new SocialActivityMsg[0];
        }

        public SocialActivitiesMsg(Std.HeaderMsg header, SocialActivityMsg[] elements)
        {
            this.header = header;
            this.elements = elements;
        }

        public static SocialActivitiesMsg Deserialize(MessageDeserializer deserializer) => new SocialActivitiesMsg(deserializer);

        private SocialActivitiesMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.elements, SocialActivityMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.elements);
            serializer.Write(this.elements);
        }

        public override string ToString()
        {
            return "SocialActivitiesMsg: " +
            "\nheader: " + header.ToString() +
            "\nelements: " + System.String.Join(", ", elements.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
