//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class TrackedPersonsMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/TrackedPersons";
        public override string RosMessageName => k_RosMessageName;

        //  Message with all currently tracked persons 
        // 
        public HeaderMsg header;
        //  Header containing timestamp etc. of this message
        public TrackedPersonMsg[] tracks;
        //  All persons that are currently being tracked

        public TrackedPersonsMsg()
        {
            this.header = new HeaderMsg();
            this.tracks = new TrackedPersonMsg[0];
        }

        public TrackedPersonsMsg(HeaderMsg header, TrackedPersonMsg[] tracks)
        {
            this.header = header;
            this.tracks = tracks;
        }

        public static TrackedPersonsMsg Deserialize(MessageDeserializer deserializer) => new TrackedPersonsMsg(deserializer);

        private TrackedPersonsMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.tracks, TrackedPersonMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.tracks);
            serializer.Write(this.tracks);
        }

        public override string ToString()
        {
            return "TrackedPersonsMsg: " +
            "\nheader: " + header.ToString() +
            "\ntracks: " + System.String.Join(", ", tracks.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
