//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class TrackedGroupMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/TrackedGroup";
        public override string RosMessageName => k_RosMessageName;

        //  Message defining a tracked group
        // 
        public string group_id;
        //  unique identifier of the target, consistent over time
        public DurationMsg age;
        //  age of the group
        public Geometry.PoseWithCovarianceMsg centerOfGravity;
        //  mean and covariance of the group (calculated from its person tracks)
        public string[] track_ids;
        //  IDs of the tracked persons in this group. See srl_tracking_msgs/TrackedPersons

        public TrackedGroupMsg()
        {
            this.group_id = "";
            this.age = new DurationMsg();
            this.centerOfGravity = new Geometry.PoseWithCovarianceMsg();
            this.track_ids = new string[0];
        }

        public TrackedGroupMsg(string group_id, DurationMsg age, Geometry.PoseWithCovarianceMsg centerOfGravity, string[] track_ids)
        {
            this.group_id = group_id;
            this.age = age;
            this.centerOfGravity = centerOfGravity;
            this.track_ids = track_ids;
        }

        public static TrackedGroupMsg Deserialize(MessageDeserializer deserializer) => new TrackedGroupMsg(deserializer);

        private TrackedGroupMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.group_id);
            this.age = DurationMsg.Deserialize(deserializer);
            this.centerOfGravity = Geometry.PoseWithCovarianceMsg.Deserialize(deserializer);
            deserializer.Read(out this.track_ids, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.group_id);
            serializer.Write(this.age);
            serializer.Write(this.centerOfGravity);
            serializer.WriteLength(this.track_ids);
            serializer.Write(this.track_ids);
        }

        public override string ToString()
        {
            return "TrackedGroupMsg: " +
            "\ngroup_id: " + group_id.ToString() +
            "\nage: " + age.ToString() +
            "\ncenterOfGravity: " + centerOfGravity.ToString() +
            "\ntrack_ids: " + System.String.Join(", ", track_ids.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
