//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class WallsMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/Walls";
        public override string RosMessageName => k_RosMessageName;

        //  A collection of line obstacles.
        //  No need to header since these are detemined at sim initiation time.
        public HeaderMsg header;
        public WallMsg[] walls;

        public WallsMsg()
        {
            this.header = new HeaderMsg();
            this.walls = new WallMsg[0];
        }

        public WallsMsg(HeaderMsg header, WallMsg[] walls)
        {
            this.header = header;
            this.walls = walls;
        }

        public static WallsMsg Deserialize(MessageDeserializer deserializer) => new WallsMsg(deserializer);

        private WallsMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.walls, WallMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.walls);
            serializer.Write(this.walls);
        }

        public override string ToString()
        {
            return "WallsMsg: " +
            "\nheader: " + header.ToString() +
            "\nwalls: " + System.String.Join(", ", walls.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
