//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class WaypointMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/Waypoint";
        public override string RosMessageName => k_RosMessageName;

        public const sbyte BHV_SIMPLE = 0;
        public const sbyte BHV_SOURCE = 1;
        public const sbyte BHV_SINK = 2;
        public string name;
        public sbyte type;
        public sbyte behavior;
        public Geometry.PointMsg position;
        public float radius;
        public float interaction_radius;

        public WaypointMsg()
        {
            this.name = "";
            this.type = 0;
            this.behavior = 0;
            this.position = new Geometry.PointMsg();
            this.radius = 0.0f;
            this.interaction_radius = 0.0f;
        }

        public WaypointMsg(string name, sbyte type, sbyte behavior, Geometry.PointMsg position, float radius, float interaction_radius)
        {
            this.name = name;
            this.type = type;
            this.behavior = behavior;
            this.position = position;
            this.radius = radius;
            this.interaction_radius = interaction_radius;
        }

        public static WaypointMsg Deserialize(MessageDeserializer deserializer) => new WaypointMsg(deserializer);

        private WaypointMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.type);
            deserializer.Read(out this.behavior);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.radius);
            deserializer.Read(out this.interaction_radius);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.type);
            serializer.Write(this.behavior);
            serializer.Write(this.position);
            serializer.Write(this.radius);
            serializer.Write(this.interaction_radius);
        }

        public override string ToString()
        {
            return "WaypointMsg: " +
            "\nname: " + name.ToString() +
            "\ntype: " + type.ToString() +
            "\nbehavior: " + behavior.ToString() +
            "\nposition: " + position.ToString() +
            "\nradius: " + radius.ToString() +
            "\ninteraction_radius: " + interaction_radius.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
