//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class CollisionMsg : Message
    {
        public const string k_RosMessageName = "unity_msgs/Collision";
        public override string RosMessageName => k_RosMessageName;

        public bool collision;

        public CollisionMsg()
        {
            this.collision = false;
        }

        public CollisionMsg(bool collision)
        {
            this.collision = collision;
        }

        public static CollisionMsg Deserialize(MessageDeserializer deserializer) => new CollisionMsg(deserializer);

        private CollisionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.collision);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.collision);
        }

        public override string ToString()
        {
            return "CollisionMsg: " +
            "\ncollision: " + collision.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
