//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class WallMsg : Message
    {
        public const string k_RosMessageName = "unity_msgs/Wall";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg start;
        public Geometry.PointMsg end;

        public WallMsg()
        {
            this.start = new Geometry.PointMsg();
            this.end = new Geometry.PointMsg();
        }

        public WallMsg(Geometry.PointMsg start, Geometry.PointMsg end)
        {
            this.start = start;
            this.end = end;
        }

        public static WallMsg Deserialize(MessageDeserializer deserializer) => new WallMsg(deserializer);

        private WallMsg(MessageDeserializer deserializer)
        {
            this.start = Geometry.PointMsg.Deserialize(deserializer);
            this.end = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start);
            serializer.Write(this.end);
        }

        public override string ToString()
        {
            return "WallMsg: " +
            "\nstart: " + start.ToString() +
            "\nend: " + end.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
