//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class AttachSafeDistSensorRequest : Message
    {
        public const string k_RosMessageName = "unity_msgs/AttachSafeDistSensor";
        public override string RosMessageName => k_RosMessageName;

        public string robot_name;
        public string safe_dist_topic;
        public bool ped_safe_dist;
        public bool obs_safe_dist;
        public double safe_dist;

        public AttachSafeDistSensorRequest()
        {
            this.robot_name = "";
            this.safe_dist_topic = "";
            this.ped_safe_dist = false;
            this.obs_safe_dist = false;
            this.safe_dist = 0.0;
        }

        public AttachSafeDistSensorRequest(string robot_name, string safe_dist_topic, bool ped_safe_dist, bool obs_safe_dist, double safe_dist)
        {
            this.robot_name = robot_name;
            this.safe_dist_topic = safe_dist_topic;
            this.ped_safe_dist = ped_safe_dist;
            this.obs_safe_dist = obs_safe_dist;
            this.safe_dist = safe_dist;
        }

        public static AttachSafeDistSensorRequest Deserialize(MessageDeserializer deserializer) => new AttachSafeDistSensorRequest(deserializer);

        private AttachSafeDistSensorRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_name);
            deserializer.Read(out this.safe_dist_topic);
            deserializer.Read(out this.ped_safe_dist);
            deserializer.Read(out this.obs_safe_dist);
            deserializer.Read(out this.safe_dist);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_name);
            serializer.Write(this.safe_dist_topic);
            serializer.Write(this.ped_safe_dist);
            serializer.Write(this.obs_safe_dist);
            serializer.Write(this.safe_dist);
        }

        public override string ToString()
        {
            return "AttachSafeDistSensorRequest: " +
            "\nrobot_name: " + robot_name.ToString() +
            "\nsafe_dist_topic: " + safe_dist_topic.ToString() +
            "\nped_safe_dist: " + ped_safe_dist.ToString() +
            "\nobs_safe_dist: " + obs_safe_dist.ToString() +
            "\nsafe_dist: " + safe_dist.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
