//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class SpawnWallsRequest : Message
    {
        public const string k_RosMessageName = "unity_msgs/SpawnWalls";
        public override string RosMessageName => k_RosMessageName;

        public string walls_string;

        public SpawnWallsRequest()
        {
            this.walls_string = "";
        }

        public SpawnWallsRequest(string walls_string)
        {
            this.walls_string = walls_string;
        }

        public static SpawnWallsRequest Deserialize(MessageDeserializer deserializer) => new SpawnWallsRequest(deserializer);

        private SpawnWallsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.walls_string);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.walls_string);
        }

        public override string ToString()
        {
            return "SpawnWallsRequest: " +
            "\nwalls_string: " + walls_string.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
