//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlebot3Example
{
    [Serializable]
    public class Turtlebot3Result : Message
    {
        public const string k_RosMessageName = "turtlebot3_example/Turtlebot3";
        public override string RosMessageName => k_RosMessageName;

        //  Define the result
        public string result;

        public Turtlebot3Result()
        {
            this.result = "";
        }

        public Turtlebot3Result(string result)
        {
            this.result = result;
        }

        public static Turtlebot3Result Deserialize(MessageDeserializer deserializer) => new Turtlebot3Result(deserializer);

        private Turtlebot3Result(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "Turtlebot3Result: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
